### ISSUE TITLE
Text elements with Font Awesome icons in them have huge hit-boxes

### ISSUE THREAD

**Issue by yuchi** [PrecursorApp/precursor#174]
When a text element has at least one Font Awesome icon in it, its hit boxes (the area available for click and rectangle selections) is huge and completely unrelated to the actual final rect of the element.

![precursor bug](https://cloud.githubusercontent.com/assets/646609/18392703/0f6e7302-76b3-11e6-954e-2a8f1917afb6.gif)

- - -

**I’d be very glad to help on this.** The codebase is a little bit intimidating, so if you can give me some pointers it would be awesome.

**Comment by dwwoelfel** [comment]
Thanks for reporting! I really appreciate your willingness to help. Since all of the issues you reported are frontend-only, I'll try to set something up so that you can develop against the production backend.

I went ahead and fixed this bug since it's been annoying me and the bug is fairly subtle.

**Comment by yuchi** [comment]
Thank you @dwwoelfel! That was pretty subtle in fact.

Let me know when you have some guidance for me to setup a dev environment or similar.

**Comment by yuchi** [comment]
Any updates on how to help you guys fix stuff?
